# Generated by Django 3.0.2 on 2020-01-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
