# Generated by Django 3.0.2 on 2020-02-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200131_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'IssueDescription',
                'verbose_name_plural': 'IssueDescriptions',
            },
        ),
    ]
